// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection
open System.Runtime.CompilerServices

[<assembly:AssemblyTitleAttribute("Feliz.Generator.Plotly")>]
[<assembly:AssemblyProductAttribute("Feliz.Plotly")>]
[<assembly:AssemblyDescriptionAttribute("Fable bindings written in the Feliz-style for plotly.js")>]
[<assembly:AssemblyVersionAttribute("0.15.0")>]
[<assembly:AssemblyFileVersionAttribute("0.15.0")>]
[<assembly:AssemblyConfigurationAttribute("Release")>]
[<assembly:InternalsVisibleToAttribute("Feliz.Generator.Plotly.Tests")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "Feliz.Generator.Plotly"

    [<Literal>]
    let AssemblyProduct = "Feliz.Plotly"

    [<Literal>]
    let AssemblyDescription = "Fable bindings written in the Feliz-style for plotly.js"

    [<Literal>]
    let AssemblyVersion = "0.15.0"

    [<Literal>]
    let AssemblyFileVersion = "0.15.0"

    [<Literal>]
    let AssemblyConfiguration = "Release"

    [<Literal>]
    let InternalsVisibleTo = "Feliz.Generator.Plotly.Tests"
