// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Feliz.Plotly")>]
[<assembly: AssemblyProductAttribute("Feliz.Plotly")>]
[<assembly: AssemblyDescriptionAttribute("Fable bindings written in the Feliz-style for plotly.js")>]
[<assembly: AssemblyVersionAttribute("0.13.0")>]
[<assembly: AssemblyFileVersionAttribute("0.13.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
[<assembly: InternalsVisibleToAttribute("Feliz.Plotly.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Feliz.Plotly"
    let [<Literal>] AssemblyProduct = "Feliz.Plotly"
    let [<Literal>] AssemblyDescription = "Fable bindings written in the Feliz-style for plotly.js"
    let [<Literal>] AssemblyVersion = "0.13.0"
    let [<Literal>] AssemblyFileVersion = "0.13.0"
    let [<Literal>] AssemblyConfiguration = "Release"
    let [<Literal>] InternalsVisibleTo = "Feliz.Plotly.Tests"
